# Uncomment the next line to define a global platform for your project
platform :ios, '14.1'

target 'Pupping' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pupping
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Crashlytics'
  pod 'ReachabilitySwift'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Kingfisher'
  pod 'TrueTime'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'FBSDKLoginKit'
  
  target 'PuppingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PuppingUITests' do
    # Pods for testing
  end

end
